/**
 * @file
 * Defintions for debug print config.
 *
 * Copyright Nuvation Research Corporation 2018-2024. All Rights Reserved.
 * www.nuvation.com
 */

#ifndef __DEBUG_PRINT_SETTINGS_H__
#define __DEBUG_PRINT_SETTINGS_H__

#define DEBUG_PRINTING 1

#define DPRINTF_RTOS 1
#define DPRINTF_USE_RAMLOG 1
#define DPRINTF_USE_RTC 1
#define DEBUG_PRINT_TASK_NAME 1
#define REBOOT_LOG_SIZE_BYTES 128
#define RAM_LOG_SIZE_BYTES (44 * 1024)

#define RAM_LOG_USART huart2 // PD5 TX, PD6 RX

#define USE_RAM_LOG_USART 1

#define DEBUG_SPI_PRINTING 0
#define DEBUG_SETTINGS_PRINTING 1
#define DEBUG_WEB_PRINTING 1
#define DEBUG_UART_PRINTING 1
#define DEBUG_JSON_PRINTING 1
#define DEBUG_MAIN_PRINTING 1
#define DEBUG_CLI_PRINTING 1
#define DEBUG_CNC_PRINTING 1
#define DEBUG_STACKQ_PRINTING 0
#define DEBUG_CTRL_COMM_PRINTING 1
#define DEBUG_DBCOMM_VERBOSE_PRINTING 0
#define DEBUG_DBCOMM_PRINTING 0
#define DEBUG_HTTPSERVER_PRINTING 0
#define DEBUG_HTTP_POST_PRINTING 0
#define DEBUG_CMD_STREAM_PRINTING 0
#define DEBUG_GATH_PRINTING 1
#define DEBUG_CMD_STREAM_VERBOSE_PRINTING 0
#define DEBUG_IMU_VERBOSE_PRINTING 0
#endif /* __DEBUG_PRINT_SETTINGS_H__ */
